# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4250350436e16d84d286aa6c86e851bdc2df7c4497d70ee985749b9a7d50a6517a5c14809cb003cefd391a568a884d6047e9ea126aaa139636bade838d8e7b02

test:
  secret_key_base: 2181f957fc9a0f95922b0e93dcb026cb95c06bf7fbd1b09da9fda69835dab74a53934f28212f1c6339d633e253d6c4233ee47626ceada43c7aeb2932a4e83413

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
